### ISSUE TITLE
Colours are incorrect on uploaded files and iframes

### ISSUE THREAD

**Issue by elliot-sawyer** [sunnysideup/silverstripe-cms-dark-theme#1]
When uploading files in the CMS, the colours are not inverted correctly on images and the thumbnails (since they are background-image rules on a div).  This is due to the contrast, saturation, and hue-rotate not being inverted.  Additionally, the CMS preview is inverted.

Original: 
![IMG_1492](https://github.com/sunnysideup/silverstripe-cms-dark-theme/assets/354793/6b37f6f6-d7a7-41e7-beb2-d419dd925658)

CMS thumbnail:
![image](https://github.com/sunnysideup/silverstripe-cms-dark-theme/assets/354793/28a97641-bc61-4cbb-a07d-b906639dc3bc)

CMS preview:
![image](https://github.com/sunnysideup/silverstripe-cms-dark-theme/assets/354793/3f8a4154-efb1-4f61-8450-7b7827538560)

**Comment by sunnysideup** [comment]
yeah, I was going to look at this. I will make the css a static so that people can tweak it as they see fit.

**Comment by elliot-sawyer** [comment]
fixed in #2
